<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.12.0" xml:lang="en-US">
  <compounddef id="class_custom_exceptions_1_1_configuration_error_exception" kind="class" language="C#" prot="public">
    <compoundname>CustomExceptions::ConfigurationErrorException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">ApplicationException</basecompoundref>
    <sectiondef kind="public-func">
      <memberdef kind="function" id="class_custom_exceptions_1_1_configuration_error_exception_1a699caec2e175ccb41183d4df331b4278" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</definition>
        <argsstring>()</argsstring>
        <name>ConfigurationErrorException</name>
        <qualifiedname>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</qualifiedname>
        <briefdescription>
<para>Initializes a new instance of the <ref refid="class_custom_exceptions_1_1_configuration_error_exception" kindref="compound">ConfigurationErrorException</ref> class with a default error message. </para>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" line="21" column="16" bodyfile="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" bodystart="21" bodyend="24"/>
      </memberdef>
      <memberdef kind="function" id="class_custom_exceptions_1_1_configuration_error_exception_1a1d0dd8fa81bfcb33ce63f4d95eae41b4" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</definition>
        <argsstring>(string error)</argsstring>
        <name>ConfigurationErrorException</name>
        <qualifiedname>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</qualifiedname>
        <param>
          <type>string</type>
          <declname>error</declname>
        </param>
        <briefdescription>
<para>Initializes a new instance of theConfigurationErrorException class with a specified error message. </para>
        </briefdescription>
        <detaileddescription>
<para><parameterlist kind="param"><parameteritem>
<parameternamelist>
<parametername>error</parametername>
</parameternamelist>
<parameterdescription>
<para>The error message that explains the reason for the exception.</para>
</parameterdescription>
</parameteritem>
</parameterlist>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" line="30" column="16" bodyfile="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" bodystart="30" bodyend="33"/>
      </memberdef>
      <memberdef kind="function" id="class_custom_exceptions_1_1_configuration_error_exception_1a96117937540c3c8996f7d76cea9ee73c" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
        <type></type>
        <definition>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</definition>
        <argsstring>(string error, Exception exception)</argsstring>
        <name>ConfigurationErrorException</name>
        <qualifiedname>CustomExceptions.ConfigurationErrorException.ConfigurationErrorException</qualifiedname>
        <param>
          <type>string</type>
          <declname>error</declname>
        </param>
        <param>
          <type>Exception</type>
          <declname>exception</declname>
        </param>
        <briefdescription>
<para>Initializes a new instance of the <ref refid="class_custom_exceptions_1_1_configuration_error_exception" kindref="compound">ConfigurationErrorException</ref> class with a specified error message and a reference to the inner exception that is the cause of this exception. </para>
        </briefdescription>
        <detaileddescription>
<para><parameterlist kind="param"><parameteritem>
<parameternamelist>
<parametername>error</parametername>
</parameternamelist>
<parameterdescription>
<para>The error message that explains the reason for the exception.</para>
</parameterdescription>
</parameteritem>
<parameteritem>
<parameternamelist>
<parametername>exception</parametername>
</parameternamelist>
<parameterdescription>
<para>The exception that is the cause of the current exception, or <computeroutput>null</computeroutput> if no inner exception is specified.</para>
</parameterdescription>
</parameteritem>
</parameterlist>
</para>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" line="40" column="16" bodyfile="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" bodystart="40" bodyend="43"/>
      </memberdef>
    </sectiondef>
    <briefdescription>
<para>Custom exception used for handling configuration-related errors in the application. </para>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="2">
        <label>ApplicationException</label>
      </node>
      <node id="1">
        <label>CustomExceptions.ConfigurationErrorException</label>
        <link refid="class_custom_exceptions_1_1_configuration_error_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="2">
        <label>ApplicationException</label>
      </node>
      <node id="1">
        <label>CustomExceptions.ConfigurationErrorException</label>
        <link refid="class_custom_exceptions_1_1_configuration_error_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" line="16" column="11" bodyfile="C:/Users/hugoc/Desktop/2024_2025/Programação Orientada a Objetos/trabalhoPOO_23010_Fase2/src/CustomExceptions/Execeptions.cs" bodystart="17" bodyend="44"/>
    <listofallmembers>
      <member refid="class_custom_exceptions_1_1_configuration_error_exception_1a699caec2e175ccb41183d4df331b4278" prot="public" virt="non-virtual"><scope>CustomExceptions::ConfigurationErrorException</scope><name>ConfigurationErrorException</name></member>
      <member refid="class_custom_exceptions_1_1_configuration_error_exception_1a1d0dd8fa81bfcb33ce63f4d95eae41b4" prot="public" virt="non-virtual"><scope>CustomExceptions::ConfigurationErrorException</scope><name>ConfigurationErrorException</name></member>
      <member refid="class_custom_exceptions_1_1_configuration_error_exception_1a96117937540c3c8996f7d76cea9ee73c" prot="public" virt="non-virtual"><scope>CustomExceptions::ConfigurationErrorException</scope><name>ConfigurationErrorException</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
